spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springDemo
    hikari:
      schema: springboot
    username: postgres
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: try
  security:
    user:
      name: Adil Qureshi
      password: '1234'

